### ISSUE TITLE
What's the third value on parameters.from and parameters.to, and what's range?

### ISSUE THREAD

**Issue by MauricioRobayo** [japhy-/scroll-scripture-parser#1]
Hi, @japhy- 👋!

This is solid, I've been testing it, thanks for putting it together.

I'm not a bible expert, just messing around with the parser... I've been struggling to understand all the fields on the returned reference object.

The parser is great and would love to see the documentation improved. 😀

For example:

```js
const scripture = require("scroll-scripture-parser");

let references = scripture.parseScripture("John 1:1-14");
```

returns:

```json
[
  {
    "type": "cv-v",
    "parameters": {
      "book": "John",
      "from": [
        1,
        1,
        ""
      ],
      "to": [
        1,
        14,
        ""
      ]
    },
    "range": [
      3211521,
      3211534
    ]
  }
]
```

Could you please provide some insight into what's the meaning of the third value in the `paramenters.from` and `parameters.to` arrays (both are empty strings)?

Also, what's the meaning of the `range` field? I can tell it is also some kind of reference, but not sure in what context or how can it be useful.

Thanks!

**Comment by jeffrey-pinyan-ithreat** [comment]
Hi @MauricioRobayo, thanks for your interest in my library. I will certainly update the code to include documentation soon.

The third parameter is the verse "fragment". Parsing _John 3:6b-9a_ would yield `{ "from": [ 3, 6, "b" ], "to": [ 3, 9, "a" ] }`.

**Comment by jeffrey-pinyan-cleandns** [comment]
> Also, what's the meaning of the `range` field? I can tell it is also some kind of reference, but not sure in what context or how can it be useful.

I just realized I never answered this part of your question.

The `range` is a numeric translation of a book, chapter, and verse. **John 1:1** translates to 3211521, which represents its book ID << 16, its chapter number << 8, and its verse number.

`const encodeReference = (book, ch, v) => parseInt(v) + (parseInt(ch) << 8) + ((Number.isInteger(book) ? book : akaToBookId[book]) << 16);`

This is used for quick range-finding. If you have a range of verses in the numeric format (e.g. John 1:1-14 represented by `[3211521, 3211534]`, and you want to know if a particular verse (e.g. John 1:6), you translate John 1:6 to its range value (3211526) and compare it to the range values.
